<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:core="http://www.govtalk.gov.uk/core" xmlns="http://www.netex.org.uk/netex" xmlns:netex="http://www.netex.org.uk/netex" targetNamespace="http://www.netex.org.uk/netex" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.2.2" id="netex_contact_version">
  <xsd:include schemaLocation="../netex_utility/netex_utility_contact.xsd"/>
  <xsd:include schemaLocation="../netex_responsibility/netex_responsibilitySet_version.xsd"/>
  <xsd:include schemaLocation="netex_contact_support.xsd"/>
  <!-- ===CONTACTS IN FRAME====Used in RESOURCE FRAME)=================================================== -->
  <xsd:complexType name="contacts_RelStructure">
    <xsd:complexContent>
      <xsd:extension base="containmentAggregationStructure">
        <xsd:sequence>
          <xsd:element ref="Contact"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- ======================================================================= -->
  <xsd:element name="Contact" substitutionGroup="DataManagedObject">
    <xsd:complexType>
      <xsd:complexContent>
        <xsd:restriction base="Contact_VersionStructure">
          <xsd:sequence>
            <xsd:sequence>
              <xsd:group ref="EntityInVersionGroup" minOccurs="0"/>
            </xsd:sequence>
            <xsd:sequence>
              <xsd:group ref="DataManagedObjectGroup"/>
            </xsd:sequence>
            <xsd:sequence>
              <xsd:group ref="ContactGroup"/>
            </xsd:sequence>
          </xsd:sequence>
          <xsd:attribute name="id" type="ContactIdType"/>
        </xsd:restriction>
      </xsd:complexContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="Contact_VersionStructure">
    <xsd:complexContent>
      <xsd:extension base="DataManagedObjectStructure">
        <xsd:sequence>
          <xsd:group ref="ContactGroup"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:group name="ContactGroup">
    <xsd:sequence>
      <xsd:element name="Name" type="MultilingualString" minOccurs="0"/>
      <xsd:element name="ContactDetails" type="ContactDetailsStructure" minOccurs="0"/>
      <xsd:element name="ContactType" type="ContactTypeEnumeration" minOccurs="0"/>
    </xsd:sequence>
  </xsd:group>
  <!-- ======================================================================= -->
</xsd:schema>
